# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from Flor import Flor
from Abeja import Abeja
from Grafo import Grafo
from Poblacion import Poblacion

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setStyleSheet("background-color:rgb(16, 24, 32)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 100, 100))
        self.frame.setStyleSheet("background-color:rgb(53, 53, 53)")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(5)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 290, 141, 81))
        self.pushButton.setStyleSheet("background-color:rgb(243, 231, 21);\n"
"color:rgb(16, 24, 32)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 290, 141, 81))
        self.pushButton_3.setStyleSheet("background-color:rgb(243, 231, 21);\n"
"color:rgb(16, 24, 32)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 180, 101, 16))
        self.label.setStyleSheet("color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 210, 91, 16))
        self.label_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 120, 111, 16))
        self.label_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 180, 47, 13))
        self.label_4.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 210, 47, 13))
        self.label_5.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 260, 121, 20))
        self.lineEdit.setStyleSheet("color:rgb(255, 255, 255)")
        self.lineEdit.setObjectName("lineEdit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 230, 131, 16))
        self.label_6.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_6.setObjectName("label_6")
        self.labelMap = QtWidgets.QLabel(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton_3.clicked.connect(lambda: self.Ugen())
        self.pushButton.clicked.connect(lambda: self.Xgens())
        self.labelMap.resize(self.frame.width(), self.frame.height())
        pixmap = QPixmap(self.frame.width(), self.frame.height())
        self.labelMap.setPixmap(pixmap)
        self.poblacion = Poblacion(self.labelMap,MainWindow)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def Xgens(self):
        x = int(self.lineEdit.text())
        if x <= 0:
            return
        else:
            self.poblacion.generaciones(x,self.label_4,self.label_5)
    def Ugen(self):
        self.poblacion.generaciones(1,self.label_4,self.label_5)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Proyecto 3 Algoritmo genetico"))
        self.pushButton.setText(_translate("MainWindow", "Iniciar simulacion completa"))
        self.pushButton_3.setText(_translate("MainWindow", "Simular una generacion"))
        self.pushButton_3.hide()
        self.label.setText(_translate("MainWindow", "Flores recolectadas"))
        self.label_2.setText(_translate("MainWindow", "Distancia recorrida"))
        self.label_3.setText(_translate("MainWindow", "Datos de la generacion final:"))
        self.label_4.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "0"))
        self.lineEdit.setText(_translate("MainWindow", "5"))
        self.label_6.setText(_translate("MainWindow", "Cantidad de generaciones:"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
